### ISSUE TITLE
Reduce Docker image size

### ISSUE THREAD

**Issue by hjball** [kanbn/kan#67]
## ✨ Feature Request

**Is your feature request related to a problem? Please describe.**
The current docker image size is ~500mb which is pretty large for a relatively simple build. This makes the regular downloads slow and storage inefficient. We should reduce this and improve the overall experience of self-hosting with the published image.

**Describe the solution you'd like**

- [ ] Reduce the docker image size
- [ ] Prevent the corepack download prompt on start

**Comment by x-sushant-x** [comment]
Hi @hjball I would like to work on this issue.

**Comment by mohsenasm** [comment]
> Prevent the corepack download prompt on start

To prevent the download on each restart, I cached `/home/nextjs/.cache`.

```yml
kind: Deployment
...
spec:
    ...
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1001: /mnt/data"]
        volumeMounts:
        - name: cache
          mountPath: /mnt/data
      containers:
      - name: kanbn
        image: ghcr.io/kanbn/kan:0.2.1
        ...
        volumeMounts:
        - name: cache
          mountPath: /home/nextjs/.cache
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: kanbn-cache
```
Although, it's probably better to take care of the download in the Dockerfile.
