### ISSUE TITLE
Unknown file extension ".sh"

### ISSUE THREAD

**Issue by cehenriques** [kanbn/kan#86]
I'm was going to try Kan using Docker compose, but when starting the container it throws this exception:

```
kan  | node:internal/modules/esm/get_format:189
kan  |   throw new ERR_UNKNOWN_FILE_EXTENSION(ext, filepath);
kan  |         ^
kan  | 
kan  | TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".sh" for /app/apps/web/entrypoint.sh
kan  |     at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:189:9)
kan  |     at defaultGetFormat (node:internal/modules/esm/get_format:232:36)
kan  |     at defaultLoad (node:internal/modules/esm/load:145:22)
kan  |     at async ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:477:45)
kan  |     at async ModuleJob._link (node:internal/modules/esm/module_job:110:19) {
kan  |   code: 'ERR_UNKNOWN_FILE_EXTENSION'
kan  | }
kan  | 
kan  | Node.js v20.19.2
```

This is my compose:

```yaml
services:
  web:
    image: ghcr.io/kanbn/kan:latest
    container_name: kan
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - shared
    ports:
      - 3002:3000
    environment:
      NEXT_PUBLIC_BASE_URL: https://kan.local.mydomain.com
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      POSTGRES_URL: ${POSTGRES_URL}
      NEXT_PUBLIC_ALLOW_CREDENTIALS: true

networks:
  shared:
    external: true
```

I'm not using the kan-db service. Instead I'm connecting to my own postgres database.

**Comment by quentains** [comment]
Just experienced the same issue. 

I took the docker-compose from the README and modified a bit to make it work with traefik :

```yaml
services:
  web:
    image: ghcr.io/kanbn/kan:latest
    container_name: kan-web
#    ports:
#      - "3000:3000"
    networks:
      - kan
      - proxy
    environment:
      NEXT_PUBLIC_BASE_URL: https://kan.my.domain
      BETTER_AUTH_SECRET: your_auth_secret
      POSTGRES_URL: postgresql://kan:your_postgres_password@postgres:5432/kan_db
      NEXT_PUBLIC_ALLOW_CREDENTIALS: true
    depends_on:
      - postgres
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.kan.loadbalancer.server.port=3000
      - traefik.http.routers.kan.entrypoints=web-secure
      - traefik.http.routers.kan.rule=Host(`kan.my.domain`)
      - traefik.http.routers.kan.tls.certresolver=myresolver
      - traefik.docker.network=proxy

  postgres:
    image: postgres:15
    container_name: kan-db
    environment:
      POSTGRES_DB: kan_db
      POSTGRES_USER: kan
      POSTGRES_PASSWORD: your_postgres_password
#    ports:
#      - 5432:5432
    volumes:
      - ./data/kan_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - kan

networks:
  proxy:
    name: proxy
    external: true
  kan:
    name: kan
```

**Comment by seesee** [comment]
I got this when setting up the docker compose as a portainer template. I added an entrypoint line to use /bin/sh (it seems to default to node) in the web service definition:
```
services:
  web:
    image: ghcr.io/kanbn/kan:latest
    entrypoint: ["/bin/sh", "/app/apps/web/entrypoint.sh"]
    container_name: kan-web
    ...

```
This at least allows the service to start although my next problem is that css/js assets etc aren't loading (NEXT_PUBLIC_BASE_URL does not appear to change anything for me)
